### ISSUE TITLE
Install XDebug

### ISSUE THREAD

**Issue by geraldnolan** [bkuhl/fpm-nginx#31]
How would you go about installing xdebug with this container?

```
COPY docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN pecl install xdebug
RUN docker-php-ext-enable xdebug
```

**Error**:
Cannot find autoconf. Please check your autoconf installation and the
$PHP_AUTOCONF environment variable. Then, rerun this script.

**Comment by RafikFarhad** [comment]
Hey @geraldnolan , I've submitted a PR which answer the issue here. You can wait for the merging the PR or you can find my repo for the Dockerfile, but in the second case you have to create your own version of docker image. 
Thank you.

**Comment by geraldnolan** [comment]
@RafikFarhad  Thank you.  I am still using image bkuhl/fpm-nginx:7.3.1

I was able to get it working via 

```
RUN apk add \
        libzip-dev \
        zip \
        $PHPIZE_DEPS \
  && docker-php-ext-configure zip --with-libzip \
  && docker-php-ext-install zip
```
```
COPY docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN pecl install xdebug
RUN docker-php-ext-enable xdebug
```
