### ISSUE TITLE
Additional Module NGINX

### ISSUE THREAD

**Issue by geraldnolan** [bkuhl/fpm-nginx#34]
I am working on integrating OPA [https://www.openpolicyagent.org/](https://www.openpolicyagent.org/) 

I need this module add to our configuration. **ngx_http_js_module**

This is in my default.conf
```
js_include /etc/nginx/conf.d/rbac.js;
location = /_authz {
    internal;
    js_content authz;
  }

  location = /_opa {
     internal;
     proxy_pass http://opa:8181/v1/data/httpapi/rbac;
  }
```

```
nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_js_module.so" failed (Error loading shared library /etc/nginx/modules/ngx_http_js_module.so: No such file or directory) in
 /etc/nginx/nginx.conf:1

```
Can you add this to the base image?

**Comment by bkuhl** [comment]
I'm not going to add this to the base image, but you can add it to the image by extending it.
