### ISSUE TITLE
Add php-geos library to FPM/Nginx docker container

### ISSUE THREAD

**Issue by MurzNN** [bkuhl/fpm-nginx#38]
Thank you for so useful container, but some PHP projects requires the `php-geos` library, that is missing. And it is unavailable in Alpine package repository, it exists only on Ubuntu and Debian for easier installing.

But for Alpine we need to compile it from sources, here is instruction: https://git.osgeo.org/gitea/geos/php-geos

So will be good to include it into your container, for extend variety of supported PHP projects.

**Comment by bkuhl** [comment]
It would be good to include this via your own application's Dockerfile.  As the base image, I plan to keep this lightweight and minimal, containing only fpm and nginx.

**Comment by MurzNN** [comment]
The suggestion was to extend script `docker-php-ext-install` to add support for installing `php-geos`, but maybe yes - it will complicate this base package.
So I've did this in my own package: https://github.com/Murz-Containers/fpm-nginx-geos
